<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\DailyPuzzle;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class DailyPuzzleSeeder extends Seeder
{
    public function run(): void
    {
        $puzzles = [
            ['fen' => 'r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 4 4',          'correct_move' => 'h5f7', 'theme' => 'Scholar\'s Mate',         'theme_lv' => 'Skolēna mats',           'explanation' => 'Qxf7# is checkmate — the queen captures f7 supported by the bishop on c4.', 'explanation_lv' => 'Dxf7# ir mats — dāma sit f7 ar laidņa c4 atbalstu.', 'difficulty' => 1],
            ['fen' => 'r2qkbnr/ppp2ppp/2np4/4N3/2B1P1b1/8/PPPP1PPP/RNBQK2R w KQkq - 2 5',               'correct_move' => 'c4f7', 'theme' => 'Fork',                    'theme_lv' => 'Dakša',                  'explanation' => 'Bxf7+ forks the king and queen after Ke7, Bb3.', 'explanation_lv' => 'Lxf7+ rada dakšu karalim un dāmai pēc Ke7, Lb3.', 'difficulty' => 1],
            ['fen' => 'rnb1k2r/ppppqppp/5n2/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 6 5',           'correct_move' => 'f3d4', 'theme' => 'Knight Outpost',          'theme_lv' => 'Zirga priekšpostenis',   'explanation' => 'Nd4 centralizes the knight with a strong outpost, attacking c6 and threatening forks.', 'explanation_lv' => 'Zd4 centralizē zirgu ar spēcīgu priekšposteni, uzbrūkot c6 un draudot ar dakšām.', 'difficulty' => 2],
            ['fen' => 'r1bqr1k1/ppp2ppp/2n2n2/3pp3/1bPP4/2N1PN2/PP3PPP/R1BQKB1R w KQ - 0 7',            'correct_move' => 'c4d5', 'theme' => 'Pawn Break',              'theme_lv' => 'Bandinieka izlaušanās',  'explanation' => 'cxd5 opens lines in the center, challenging Black\'s pawn structure.', 'explanation_lv' => 'cxd5 atver līnijas centrā, izaicinot melnā bandinieku struktūru.', 'difficulty' => 2],
            ['fen' => '6k1/5ppp/8/8/8/8/5PPP/4R1K1 w - - 0 1',                                           'correct_move' => 'e1e8', 'theme' => 'Back Rank Mate',          'theme_lv' => 'Pēdējās rindas mats',   'explanation' => 'Re8# is checkmate — the king is trapped by its own pawns.', 'explanation_lv' => 'Te8# ir mats — karalis ir iesprostots starp saviem bandiniēkiem.', 'difficulty' => 1],
            ['fen' => 'r3k2r/ppp2ppp/2n1bn2/3qp3/3P4/2N1BN2/PPP2PPP/R2QK2R w KQkq - 0 8',               'correct_move' => 'd4e5', 'theme' => 'Discovered Attack',       'theme_lv' => 'Atklātais uzbrukums',   'explanation' => 'dxe5 discovers an attack on the queen from the bishop on e3.', 'explanation_lv' => 'dxe5 atklāj uzbrukumu dāmai no laidņa e3.', 'difficulty' => 2],
            ['fen' => 'r1b1kb1r/ppppqppp/2n2n2/1B2p3/4P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 6 5',          'correct_move' => 'b5c6', 'theme' => 'Exchange Sacrifice',     'theme_lv' => 'Apmaiņas upuris',       'explanation' => 'Bxc6 damages Black\'s pawn structure and opens the d-file.', 'explanation_lv' => 'Lxc6 sabojā melnā bandinieku struktūru un atver d-līniju.', 'difficulty' => 2],
            ['fen' => '2rq1rk1/pp2ppbp/2np1np1/8/2PNP3/2N1BP2/PP4PP/R2Q1RK1 w - - 0 12',                 'correct_move' => 'd4c6', 'theme' => 'Knight Sacrifice',       'theme_lv' => 'Zirga upuris',          'explanation' => 'Nxc6 wins material — bxc6 allows Bxa7 with a pawn advantage.', 'explanation_lv' => 'Zxc6 iegūst materiālu — bxc6 ļauj Lxa7 ar bandinieku pārsvaru.', 'difficulty' => 2],
            ['fen' => 'r2q1rk1/ppp1bppp/2n5/3np3/8/P1N1P1P1/1PP1NPBP/R2QK2R b KQ - 0 10',               'correct_move' => 'd5c3', 'theme' => 'Tactic: Remove Guard',   'theme_lv' => 'Taktika: Aizstāvja noņemšana', 'explanation' => 'Nxc3 removes the defender and wins material after bxc3, Bxc3.', 'explanation_lv' => 'Zxc3 noņem aizstāvi un iegūst materiālu pēc bxc3, Lxc3.', 'difficulty' => 2],
            ['fen' => '1r4k1/p4ppp/2p1p3/8/3qP3/5Q2/PPP2PPP/R4RK1 w - - 0 1',                           'correct_move' => 'f3f7', 'theme' => 'Queen Infiltration',     'theme_lv' => 'Dāmas iefiltrēšanās',   'explanation' => 'Qf7+ leads to a forced sequence winning material.', 'explanation_lv' => 'Df7+ uzsāk piespiedu secību, kas iegūst materiālu.', 'difficulty' => 2],
            ['fen' => 'r1bqk2r/pppp1Bpp/2n2n2/2b1p3/4P3/2N2N2/PPPP1PPP/R1BQK2R b KQkq - 0 4',           'correct_move' => 'e8f7', 'theme' => 'Recapture',              'theme_lv' => 'Atsitiena gājiens',      'explanation' => 'Kxf7 recaptures the bishop, though Black has lost castling rights.', 'explanation_lv' => 'Kxf7 sit laidni, bet melnie zaudē rokādes tiesības.', 'difficulty' => 1],
            ['fen' => 'r3r1k1/ppp2ppp/5n2/3q4/3P4/2P2N2/P4PPP/R2QR1K1 w - - 0 1',                       'correct_move' => 'e1e8', 'theme' => 'Pin',                    'theme_lv' => 'Saspraušana',            'explanation' => 'Rxe8+ exploits the pin on the e-file — the rook is hanging.', 'explanation_lv' => 'Txe8+ izmanto saspraušanu uz e-līnijas — tornis ir neaizsargāts.', 'difficulty' => 2],
            ['fen' => 'r1bqk2r/pppp1ppp/2n2n2/4p3/1bB1P3/2N2N2/PPPP1PPP/R1BQ1RK1 b kq - 5 4',           'correct_move' => 'b4c3', 'theme' => 'Bishop Exchange',        'theme_lv' => 'Laidņu apmaiņa',        'explanation' => 'Bxc3 doubles White\'s pawns and weakens the queenside.', 'explanation_lv' => 'Lxc3 dubulto baltā bandiniekus un vājina dāmas flangu.', 'difficulty' => 1],
            ['fen' => '2kr3r/ppq2ppp/4pn2/2Pp4/3P4/2NBPN2/PP3PPP/R2Q1RK1 w - - 0 11',                 'correct_move' => 'c5c6', 'theme' => 'Pawn Advance',           'theme_lv' => 'Bandinieka virzīšana',  'explanation' => 'c6! undermines the defense and opens lines against the king.', 'explanation_lv' => 'c6! graujas zem aizsardzības un atver līnijas pret karali.', 'difficulty' => 3],
            ['fen' => 'r4rk1/pp3ppp/2p1pn2/q3N3/2PP4/4B3/PP3PPP/R2Q1RK1 w - - 0 1',                     'correct_move' => 'e5c6', 'theme' => 'Knight Fork',            'theme_lv' => 'Zirga dakša',           'explanation' => 'Nxc6! forks the queen on a5 and the rook on a8.', 'explanation_lv' => 'Zxc6! rada dakšu dāmai a5 un tornim a8.', 'difficulty' => 2],
            ['fen' => 'r1b2rk1/2q1bppp/p1n1pn2/1p6/3NP3/2N1B3/PPP1BPPP/R2Q1RK1 w - - 0 10',             'correct_move' => 'd4c6', 'theme' => 'Central Control',        'theme_lv' => 'Centra kontrole',       'explanation' => 'Nxc6 captures the knight, and after Qxc6, White has a strong center.', 'explanation_lv' => 'Zxc6 sit zirgu, pēc Dxc6 baltajam ir spēcīgs centrs.', 'difficulty' => 2],
            ['fen' => '6k1/pp3pp1/2p4p/4p3/4P3/1P4PP/P1r2PK1/3R4 w - - 0 1',                             'correct_move' => 'd1d8', 'theme' => 'Rook Endgame',           'theme_lv' => 'Torņu galotne',         'explanation' => 'Rd8+ activates the rook with check, securing a dominant position.', 'explanation_lv' => 'Td8+ aktivizē torni ar šahu, nodrošinot dominējošu pozīciju.', 'difficulty' => 2],
            ['fen' => 'r1bq1rk1/ppppnppp/4p3/8/1bBP4/2N1P3/PPP2PPP/R1BQ1RK1 w - - 0 7',                  'correct_move' => 'c4e6', 'theme' => 'Bishop Sacrifice',      'theme_lv' => 'Laidņa upuris',         'explanation' => 'Bxe6 sacrifices the bishop to weaken the kingside pawn cover.', 'explanation_lv' => 'Lxe6 upurē laidni, lai vājinātu karaļa flangu.', 'difficulty' => 3],
            ['fen' => 'r1bqkb1r/pp1ppppp/2n5/2p1n3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 4 4',             'correct_move' => 'f3e5', 'theme' => 'Knight Capture',         'theme_lv' => 'Zirga sitiens',         'explanation' => 'Nxe5 wins a pawn — the knight on e5 was only protected by the c6 knight.', 'explanation_lv' => 'Zxe5 iegūst bandinieku — zirgu e5 aizsargāja tikai zirgs c6.', 'difficulty' => 1],
            ['fen' => 'r2qk2r/ppp1bppp/2n2n2/3pp1B1/2B1P3/3P1N2/PPP2PPP/RN1QK2R w KQkq - 0 6',          'correct_move' => 'g5f6', 'theme' => 'Pin Exploitation',       'theme_lv' => 'Saspraušanas izmantošana', 'explanation' => 'Bxf6 exploits the pin on the e7 bishop.', 'explanation_lv' => 'Lxf6 izmanto saspraušanu uz e7 laidņa.', 'difficulty' => 2],
            // Additional 70 puzzles for ~3 months coverage
            ['fen' => '2r3k1/pp3ppp/4p3/2b5/4P3/2N2P2/PPr3PP/2R2RK1 b - - 0 1',        'correct_move' => 'c2c3', 'theme' => 'Rook on 7th', 'theme_lv' => 'Tornis 7. rindā', 'explanation' => 'Rxc3 wins the knight.', 'explanation_lv' => 'Txc3 iegūst zirgu.', 'difficulty' => 1],
            ['fen' => 'r4rk1/ppp1qppp/2n2n2/4p3/2B1P3/2NP4/PPP2PPP/R2Q1RK1 w - - 0 8', 'correct_move' => 'c4f7', 'theme' => 'Sacrifice', 'theme_lv' => 'Upuris', 'explanation' => 'Bxf7+ wins the exchange.', 'explanation_lv' => 'Lxf7+ iegūst apmaiņu.', 'difficulty' => 2],
            ['fen' => '3r2k1/pp3pp1/4p2p/8/3P4/2P1B3/P4PPP/3R2K1 w - - 0 1',            'correct_move' => 'd1d8', 'theme' => 'Back Rank', 'theme_lv' => 'Pēdējā rinda', 'explanation' => 'Rd8# is back rank mate.', 'explanation_lv' => 'Td8# ir pēdējās rindas mats.', 'difficulty' => 1],
            ['fen' => 'r1bq1rk1/pppp1ppp/2n2n2/2b1p3/2B1P3/3P1N2/PPP2PPP/RNBQ1RK1 w - - 4 5', 'correct_move' => 'c1g5', 'theme' => 'Pin', 'theme_lv' => 'Saspraušana', 'explanation' => 'Bg5 pins the knight to the queen.', 'explanation_lv' => 'Lg5 saspiež zirgu pret dāmu.', 'difficulty' => 1],
            ['fen' => 'r1b1k2r/ppp2ppp/2n1pn2/3p4/1bPP4/2N1PN2/PP3PPP/R1BQKB1R w KQkq - 0 5', 'correct_move' => 'c4d5', 'theme' => 'Central Break', 'theme_lv' => 'Centra izlaušanās', 'explanation' => 'cxd5 opens the center.', 'explanation_lv' => 'cxd5 atver centru.', 'difficulty' => 2],
            ['fen' => 'r2q1rk1/1pp2ppp/p1n1bn2/3pp3/4P3/1BN2N2/PPP2PPP/R1BQ1RK1 w - - 0 9', 'correct_move' => 'e4d5', 'theme' => 'Pawn Tension', 'theme_lv' => 'Bandinieku spriedze', 'explanation' => 'exd5 resolves the tension favorably.', 'explanation_lv' => 'exd5 izšķir spriedzi izdevīgi.', 'difficulty' => 2],
            ['fen' => '5rk1/pp2ppbp/6p1/2p5/2P5/2N2B2/PP3PPP/3R2K1 w - - 0 1',          'correct_move' => 'd1d7', 'theme' => 'Rook Penetration', 'theme_lv' => 'Torņa ielaušanās', 'explanation' => 'Rd7 penetrates to the 7th rank.', 'explanation_lv' => 'Td7 ielaužas 7. rindā.', 'difficulty' => 2],
            ['fen' => 'r1bqk2r/pppp1ppp/2n2n2/4N3/2B1P3/8/PPPP1PPP/RNBQK2R b KQkq - 0 4', 'correct_move' => 'd7d5', 'theme' => 'Counter-attack', 'theme_lv' => 'Pretuzbrukums', 'explanation' => 'd5 counter-attacks the center while the knight is hanging.', 'explanation_lv' => 'd5 pretuzbŗūk centram kamēr zirgs ir neaizsargāts.', 'difficulty' => 2],
            ['fen' => '4r1k1/ppp2ppp/2n5/3q4/8/2N2B2/PPP2PPP/R2Q1RK1 b - - 0 1',        'correct_move' => 'd5d1', 'theme' => 'Queen Trade', 'theme_lv' => 'Dāmu apmaiņa', 'explanation' => 'Qd1 forces a favorable queen trade.', 'explanation_lv' => 'Dd1 piespiež izdevīgu dāmu apmaiņu.', 'difficulty' => 2],
            ['fen' => 'r1bqk2r/ppppnppp/2n5/2b1p3/2B1P3/2N2N2/PPPP1PPP/R1BQK2R w KQkq - 4 4', 'correct_move' => 'd2d4', 'theme' => 'Center Control', 'theme_lv' => 'Centra kontrole', 'explanation' => 'd4 strikes at the center immediately.', 'explanation_lv' => 'd4 uzreiz sitiens centrā.', 'difficulty' => 1],
            ['fen' => 'r3kb1r/ppp1pppp/2n2n2/3q4/3P4/2N2N2/PPP2PPP/R1BQKB1R b KQkq - 0 5', 'correct_move' => 'd5a5', 'theme' => 'Queen Activity', 'theme_lv' => 'Dāmas aktivitāte', 'explanation' => 'Qa5 develops the queen to an active square.', 'explanation_lv' => 'Da5 izvieto dāmu aktīvā pozīcijā.', 'difficulty' => 1],
            ['fen' => '2kr4/ppp2ppp/2n5/3p4/3P1B2/2P5/PP3PPP/R3K2R w KQ - 0 1',          'correct_move' => 'f4c7', 'theme' => 'Bishop Infiltration', 'theme_lv' => 'Laidņa iefiltrēšanās', 'explanation' => 'Bc7 traps the rook.', 'explanation_lv' => 'Lc7 iesloga torni.', 'difficulty' => 2],
            ['fen' => 'r4rk1/pp1b1ppp/2p1pn2/q7/2PP4/2N1PN2/PP3PPP/R2QKB1R w KQ - 0 8', 'correct_move' => 'c3e4', 'theme' => 'Knight Jump', 'theme_lv' => 'Zirga lēciens', 'explanation' => 'Ne4 centralizes the knight threatening Nd6.', 'explanation_lv' => 'Ze4 centralizē zirgu draudot ar Zd6.', 'difficulty' => 2],
            ['fen' => '6k1/5pp1/p2p3p/1p1P4/1P2PP2/P5PP/8/6K1 w - - 0 1',                'correct_move' => 'e4e5', 'theme' => 'Pawn Endgame', 'theme_lv' => 'Bandinieku galotne', 'explanation' => 'e5 creates a passed pawn.', 'explanation_lv' => 'e5 izveido brīvo bandinieku.', 'difficulty' => 2],
            ['fen' => 'r1bq1rk1/ppp1nppp/3p1n2/3Pp3/2P5/2N2N2/PP2PPPP/R1BQKB1R w KQ - 0 7', 'correct_move' => 'c3d5', 'theme' => 'Outpost', 'theme_lv' => 'Priekšpostenis', 'explanation' => 'Nd5 occupies the ideal outpost.', 'explanation_lv' => 'Zd5 ieņem ideālo priekšposteni.', 'difficulty' => 2],
            ['fen' => 'r2qr1k1/pp2bppp/2n2n2/3p4/3P4/2NBPN2/PP3PPP/R2QK2R w KQ - 0 9', 'correct_move' => 'e3e4', 'theme' => 'Central Advance', 'theme_lv' => 'Centrālā virzīšana', 'explanation' => 'e4 gains space in the center.', 'explanation_lv' => 'e4 iegūst telpu centrā.', 'difficulty' => 2],
            ['fen' => 'r1b2rk1/ppq2ppp/2n1pn2/2pp4/3P4/2PBPN2/PP1N1PPP/R2Q1RK1 w - - 0 8', 'correct_move' => 'd4c5', 'theme' => 'Pawn Exchange', 'theme_lv' => 'Bandinieku apmaiņa', 'explanation' => 'dxc5 opens the d-file.', 'explanation_lv' => 'dxc5 atver d-līniju.', 'difficulty' => 1],
            ['fen' => '1r3rk1/p4ppp/2p1p3/3p4/3P1B2/4PN2/PP3PPP/R4RK1 w - - 0 1',       'correct_move' => 'f3e5', 'theme' => 'Knight Attack', 'theme_lv' => 'Zirga uzbrukums', 'explanation' => 'Ne5 targets the weak c6 pawn.', 'explanation_lv' => 'Ze5 mērķē uz vājo c6 bandinieku.', 'difficulty' => 2],
            ['fen' => 'r3r1k1/ppp2ppp/2n1bn2/3p4/3P4/2NBPN2/PP3PPP/R3K2R w KQ - 0 8',   'correct_move' => 'e1g1', 'theme' => 'Castling', 'theme_lv' => 'Rokāde', 'explanation' => 'O-O completes development and secures the king.', 'explanation_lv' => 'O-O pabeidz izstrādi un nodrošina karaļa drošību.', 'difficulty' => 1],
            ['fen' => 'r2qkb1r/ppp2ppp/2n1pn2/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 0 4', 'correct_move' => 'c4d5', 'theme' => 'Exchange Variation', 'theme_lv' => 'Apmaiņas variants', 'explanation' => 'cxd5 enters the exchange variation.', 'explanation_lv' => 'cxd5 ieiet apmaiņas variantā.', 'difficulty' => 1],
            ['fen' => 'rnbqk2r/ppp1ppbp/5np1/3p4/2PP4/2N2N2/PP2PPPP/R1BQKB1R w KQkq - 0 4', 'correct_move' => 'c4d5', 'theme' => 'Grünfeld Exchange', 'theme_lv' => 'Grünfelda apmaiņa', 'explanation' => 'cxd5 is the main line Grünfeld exchange.', 'explanation_lv' => 'cxd5 ir galvenais Grünfelda apmaiņas variants.', 'difficulty' => 2],
            ['fen' => 'r1b1kb1r/ppppqppp/2n5/4p3/2B1n3/5N2/PPPP1PPP/RNBQR1K1 w kq - 0 5', 'correct_move' => 'c4f7', 'theme' => 'Italian Sacrifice', 'theme_lv' => 'Itāliešu upuris', 'explanation' => 'Bxf7+ wins material with check.', 'explanation_lv' => 'Lxf7+ iegūst materiālu ar šahu.', 'difficulty' => 2],
            ['fen' => 'r1bqk2r/1pppbppp/p1n2n2/4p3/B3P3/5N2/PPPP1PPP/RNBQ1RK1 w kq - 0 5', 'correct_move' => 'f1e1', 'theme' => 'Ruy Lopez', 'theme_lv' => 'Spāņu partija', 'explanation' => 'Re1 supports the e4 pawn and prepares d4.', 'explanation_lv' => 'Te1 atbalsta e4 bandinieku un sagatavo d4.', 'difficulty' => 2],
            ['fen' => 'r3k2r/ppp2ppp/2n1bn2/3qp3/8/2NP1NP1/PPP1PPBP/R2QK2R w KQkq - 0 7', 'correct_move' => 'e1g1', 'theme' => 'King Safety', 'theme_lv' => 'Karaļa drošība', 'explanation' => 'O-O is the priority — king safety first.', 'explanation_lv' => 'O-O ir prioritāte — karaļa drošība pirmkārt.', 'difficulty' => 1],
            ['fen' => '2r1rbk1/pp3ppp/2n1p3/3pP3/5P2/2N2N2/PPP3PP/2KR1B1R w - - 0 1',     'correct_move' => 'f3d4', 'theme' => 'Knight Centralization', 'theme_lv' => 'Zirga centralizācija', 'explanation' => 'Nd4 occupies the strongest central square.', 'explanation_lv' => 'Zd4 ieņem spēcīgāko centrālo laukumu.', 'difficulty' => 2],
            ['fen' => 'r2q1rk1/pp2ppbp/3p1np1/2pP4/4P3/2N2N2/PP2BPPP/R1BQ1RK1 w - - 0 9', 'correct_move' => 'e4e5', 'theme' => 'Space Advantage', 'theme_lv' => 'Telpas pārsvars', 'explanation' => 'e5 gains significant space on the kingside.', 'explanation_lv' => 'e5 iegūst ievērojamu telpu karaļa flangā.', 'difficulty' => 2],
            ['fen' => 'r1bq1rk1/pppn1ppp/4pn2/3p4/2PP4/2NBPN2/PP3PPP/R1BQ1RK1 w - - 0 7', 'correct_move' => 'c4c5', 'theme' => 'Minority Attack', 'theme_lv' => 'Minoritātes uzbrukums', 'explanation' => 'c5 starts a minority attack on the queenside.', 'explanation_lv' => 'c5 sāk minoritātes uzbrukumu dāmas flangā.', 'difficulty' => 3],
            ['fen' => 'r2q1rk1/pppbbppp/4pn2/3p4/3P4/3BPN2/PPP2PPP/RN1Q1RK1 w - - 0 7',  'correct_move' => 'b1d2', 'theme' => 'Development', 'theme_lv' => 'Izstrāde', 'explanation' => 'Nbd2 completes minor piece development.', 'explanation_lv' => 'Zbd2 pabeidz vieglo figūru izstrādi.', 'difficulty' => 1],
            ['fen' => '2rr2k1/pp3ppp/2n1p3/3pP3/3P4/2PB4/PP3PPP/R3R1K1 w - - 0 1',       'correct_move' => 'd3h7', 'theme' => 'Greek Gift', 'theme_lv' => 'Grieķu dāvana', 'explanation' => 'Bxh7+ is the classic Greek Gift sacrifice.', 'explanation_lv' => 'Lxh7+ ir klasisks grieķu dāvanas upuris.', 'difficulty' => 3],
            ['fen' => 'r4rk1/pppq1ppp/2n1pn2/3p2B1/3P4/2NBPN2/PPP2PPP/R2Q1RK1 w - - 0 8', 'correct_move' => 'g5h4', 'theme' => 'Retreat', 'theme_lv' => 'Atkāpšanās', 'explanation' => 'Bh4 maintains the pin and avoids exchange.', 'explanation_lv' => 'Lh4 saglabā saspraušanu un izvairās no apmaiņas.', 'difficulty' => 2],
            ['fen' => 'rnbqk2r/pp3ppp/4pn2/2pp4/1bPP4/2N1PN2/PP3PPP/R1BQKB1R w KQkq - 0 5', 'correct_move' => 'a2a3', 'theme' => 'Bishop Pressure', 'theme_lv' => 'Laidņa spiediens', 'explanation' => 'a3 asks the bishop to commit or retreat.', 'explanation_lv' => 'a3 prasa laidnim izlemt — palikt vai atkāpties.', 'difficulty' => 1],
            ['fen' => 'r1bqr1k1/pp3ppp/2n1pn2/3p4/2PP4/5NP1/PP2PPBP/R1BQ1RK1 w - - 0 8', 'correct_move' => 'c4d5', 'theme' => 'Catalan Exchange', 'theme_lv' => 'Katalāņu apmaiņa', 'explanation' => 'cxd5 opens the long diagonal for the g2 bishop.', 'explanation_lv' => 'cxd5 atver garo diagonāli g2 laidnim.', 'difficulty' => 2],
            ['fen' => 'r1bq1rk1/ppp2ppp/2np1n2/2b1p3/2B1P3/2NP1N2/PPP2PPP/R1BQ1RK1 w - - 0 6', 'correct_move' => 'c1e3', 'theme' => 'Bishop Development', 'theme_lv' => 'Laidņa izstrāde', 'explanation' => 'Be3 develops with tempo threatening the c5 bishop.', 'explanation_lv' => 'Le3 izstrādājas ar tempu draudot c5 laidnim.', 'difficulty' => 1],
            ['fen' => '1k1r4/pp3ppp/4p3/2p5/2P5/1P3P2/P4KPP/3R4 w - - 0 1',              'correct_move' => 'd1d7', 'theme' => 'Rook Endgame Activity', 'theme_lv' => 'Torņa galotnes aktivitāte', 'explanation' => 'Rd7 penetrates the 7th rank targeting pawns.', 'explanation_lv' => 'Td7 ielaužas 7. rindā mērķējot uz bandiniēkiem.', 'difficulty' => 2],
            ['fen' => '3r2k1/p4ppp/1p2p3/2p5/2P5/1P3NP1/P4PKP/3R4 w - - 0 1',            'correct_move' => 'f3e5', 'theme' => 'Knight vs Rook Endgame', 'theme_lv' => 'Zirgs pret torni galotnē', 'explanation' => 'Ne5 centralizes with threats to f7 and d7.', 'explanation_lv' => 'Ze5 centralizējas draudot f7 un d7.', 'difficulty' => 2],
            ['fen' => 'r3k2r/pp1b1ppp/2n1pn2/2ppN3/3P4/2PBPN2/PP3PPP/R2QK2R w KQkq - 0 7', 'correct_move' => 'e5c6', 'theme' => 'Destruction', 'theme_lv' => 'Iznīcināšana', 'explanation' => 'Nxc6 destroys the defender of d5.', 'explanation_lv' => 'Zxc6 iznīcina d5 aizstāvi.', 'difficulty' => 2],
            ['fen' => 'r1b2rk1/2q1bppp/p1nppn2/1p4B1/3NP3/1BN5/PPP2PPP/R2Q1RK1 w - - 0 10', 'correct_move' => 'd4c6', 'theme' => 'Exchange Sac', 'theme_lv' => 'Apmaiņas upuris', 'explanation' => 'Nxc6 followed by Nd5 dominates.', 'explanation_lv' => 'Zxc6 kam seko Zd5 dominē.', 'difficulty' => 3],
            ['fen' => '5k2/p4ppp/1p6/2p5/P1P5/1P4P1/5PKP/8 w - - 0 1',                   'correct_move' => 'a4a5', 'theme' => 'Passed Pawn', 'theme_lv' => 'Brīvais bandinieks', 'explanation' => 'a5 creates a passed pawn on the queenside.', 'explanation_lv' => 'a5 izveido brīvo bandinieku dāmas flangā.', 'difficulty' => 2],
            ['fen' => '8/8/4kpp1/3p1b2/p6P/2B5/6P1/6K1 w - - 0 1',                        'correct_move' => 'h4h5', 'theme' => 'Pawn Breakthrough', 'theme_lv' => 'Bandinieka caursitiens', 'explanation' => 'h5 breaks through the kingside pawns.', 'explanation_lv' => 'h5 caursit karaļa flanga bandiniekus.', 'difficulty' => 3],
            ['fen' => '6k1/pp2rp1p/2p1p1p1/8/2PP4/4P1P1/PP2KP1P/3R4 w - - 0 1',          'correct_move' => 'd4d5', 'theme' => 'Pawn Break', 'theme_lv' => 'Bandinieka laušana', 'explanation' => 'd5 opens lines in the center.', 'explanation_lv' => 'd5 atver līnijas centrā.', 'difficulty' => 2],
            ['fen' => 'r2qkbnr/pp1bpppp/2np4/1B6/3NP3/8/PPP2PPP/RNBQK2R w KQkq - 0 5',  'correct_move' => 'b5c6', 'theme' => 'Double Pawns', 'theme_lv' => 'Dubultie bandinieki', 'explanation' => 'Bxc6 doubles Black\'s pawns.', 'explanation_lv' => 'Lxc6 dubulto melnā bandiniekus.', 'difficulty' => 1],
            ['fen' => 'r1b1r1k1/pp3ppp/1qnp1n2/2p1p3/2P1P3/2NP1N2/PP2BPPP/R1BQ1RK1 w - - 0 8', 'correct_move' => 'a2a4', 'theme' => 'Flank Attack', 'theme_lv' => 'Flanga uzbrukums', 'explanation' => 'a4 starts a queenside expansion.', 'explanation_lv' => 'a4 sāk dāmas flanga paplašināšanos.', 'difficulty' => 2],
        ];

        $startDate = Carbon::today();

        foreach ($puzzles as $i => $puzzle) {
            DailyPuzzle::updateOrCreate(
                ['puzzle_date' => $startDate->copy()->addDays($i)->toDateString()],
                $puzzle,
            );
        }

        // Also seed some past puzzles for history
        foreach (array_slice($puzzles, 0, 10) as $i => $puzzle) {
            DailyPuzzle::updateOrCreate(
                ['puzzle_date' => $startDate->copy()->subDays($i + 1)->toDateString()],
                $puzzle,
            );
        }
    }
}
