<?php

namespace Database\Seeders;

use App\Models\Opening;
use Illuminate\Database\Seeder;

class OpeningSeeder extends Seeder
{
    public function run(): void
    {
        Opening::query()->delete();

        $openings = [
            ['g3', 'A00', 'Benko Opening', 'Benko atklātne', 'A'],
            ['b3', 'A01', 'Nimzo-Larsen Attack', 'Nimcoviča-Laršena uzbrukums', 'A'],
            ['f4', 'A02', "Bird's Opening", 'Bērda atklātne', 'A'],
            ['Nf3 d5 c4', 'A09', 'Réti Opening', 'Rēti atklātne', 'A'],
            ['Nf3 d5', 'A07', "King's Indian Attack", 'Karaļa indiešu uzbrukums', 'A'],
            ['Nf3 Nf6', 'A05', 'Réti Opening', 'Rēti atklātne', 'A'],
            ['Nf3', 'A04', 'Réti Opening', 'Rēti atklātne', 'A'],
            ['c4 e5 Nc3 Nf6', 'A28', 'English Opening, Four Knights', 'Angļu atklātne, četru jātnieku variante', 'A'],
            ['c4 e5 Nc3', 'A25', 'English Opening, Sicilian Reversed', 'Angļu atklātne, Sicīliešu inversija', 'A'],
            ['c4 c6', 'A11', 'English Opening, Caro-Kann setup', 'Angļu atklātne, Karo-Kann setup', 'A'],
            ['c4 e6', 'A13', 'English Opening', 'Angļu atklātne', 'A'],
            ['c4 c5', 'A30', 'English Opening, Symmetrical', 'Angļu atklātne, simetriskā', 'A'],
            ['c4 e5', 'A20', 'English Opening', 'Angļu atklātne', 'A'],
            ['c4 Nf6', 'A15', 'English Opening', 'Angļu atklātne', 'A'],
            ['c4', 'A10', 'English Opening', 'Angļu atklātne', 'A'],
            ['d4 f5', 'A80', 'Dutch Defence', 'Holandiešu aizsardzība', 'A'],
            ['d4 c5', 'A43', 'Old Benoni Defence', 'Benoni aizsardzība', 'A'],
            ['d4 Nf6 c4 c5 d5', 'A56', 'Benoni Defence', 'Benoni aizsardzība', 'A'],
            ['e4 d5 exd5 Qxd5', 'B01', 'Scandinavian Defence, Main Line', 'Skandināvu aizsardzība, galvenā līnija', 'B'],
            ['e4 d5 exd5 Nf6', 'B01', 'Scandinavian Defence, 2...Nf6', 'Skandināvu aizsardzība, 2...Nf6', 'B'],
            ['e4 d5', 'B01', 'Scandinavian Defence', 'Skandināvu aizsardzība', 'B'],
            ['e4 d6 d4 Nf6 Nc3 g6', 'B08', 'Pirc Defence, Classical', 'Pīrca aizsardzība, klasiskā', 'B'],
            ['e4 d6 d4 Nf6 Nc3', 'B07', 'Pirc Defence', 'Pīrca aizsardzība', 'B'],
            ['e4 d6', 'B07', 'Pirc Defence (general)', 'Pīrca aizsardzība (vispārīgā)', 'B'],
            ['e4 g6', 'B06', 'Modern Defence', 'Modernā aizsardzība', 'B'],
            ['e4 c6 d4 d5 Nc3 dxe4 Nxe4', 'B17', 'Caro-Kann, Steinitz', 'Karo-Kann, Šteininca variante', 'B'],
            ['e4 c6 d4 d5 e5', 'B12', 'Caro-Kann, Advance', 'Karo-Kann, avansu variante', 'B'],
            ['e4 c6 d4 d5 Nc3', 'B15', 'Caro-Kann, Main Line', 'Karo-Kann, galvenā līnija', 'B'],
            ['e4 c6 d4 d5', 'B12', 'Caro-Kann Defence', 'Karo-Kann aizsardzība', 'B'],
            ['e4 c6', 'B10', 'Caro-Kann Defence', 'Karo-Kann aizsardzība', 'B'],
            ['e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6', 'B90', 'Sicilian, Najdorf', 'Sicīliešu aizsardzība, Nadžorfa variante', 'B'],
            ['e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6', 'B76', 'Sicilian, Dragon', 'Sicīliešu aizsardzība, Pūķa variante', 'B'],
            ['e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e5', 'B33', 'Sicilian, Sveshnikov', 'Sicīliešu aizsardzība, Svešņikova variante', 'B'],
            ['e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3', 'B56', 'Sicilian, Open', 'Sicīliešu aizsardzība, atvērtā', 'B'],
            ['e4 c5 Nf3 Nc6 Bb5', 'B31', 'Sicilian, Rossolimo', 'Sicīliešu aizsardzība, Rossolimo variante', 'B'],
            ['e4 c5 Nc3', 'B23', 'Sicilian, Closed', 'Sicīliešu aizsardzība, slēgtā', 'B'],
            ['e4 c5 c3', 'B22', 'Sicilian, Alapin', 'Sicīliešu aizsardzība, Alapina variante', 'B'],
            ['e4 c5 Nf3 d6', 'B50', 'Sicilian Defence', 'Sicīliešu aizsardzība', 'B'],
            ['e4 c5 Nf3', 'B27', 'Sicilian Defence', 'Sicīliešu aizsardzība', 'B'],
            ['e4 c5', 'B20', 'Sicilian Defence', 'Sicīliešu aizsardzība', 'B'],
            ['e4 e6 d4 d5 Nc3 Bb4', 'C15', 'French, Winawer', 'Francūzu aizsardzība, Vinawera variante', 'C'],
            ['e4 e6 d4 d5 Nc3 Nf6', 'C10', 'French, Classical', 'Francūzu aizsardzība, klasiskā', 'C'],
            ['e4 e6 d4 d5 Nd2', 'C01', 'French, Tarrasch', 'Francūzu aizsardzība, Tarraša variante', 'C'],
            ['e4 e6 d4 d5 e5', 'C02', 'French, Advance', 'Francūzu aizsardzība, avansu variante', 'C'],
            ['e4 e6 d4 d5', 'C00', 'French Defence', 'Francūzu aizsardzība', 'C'],
            ['e4 e6', 'C00', 'French Defence (general)', 'Francūzu aizsardzība (vispārīgā)', 'C'],
            ['e4 e5 f4', 'C30', "King's Gambit", 'Karaļa gambīts', 'C'],
            ['e4 e5 Nf3 Nf6', 'C42', "Petrov's Defence", 'Petrova aizsardzība', 'C'],
            ['e4 e5 Nf3 Nc6 d4', 'C44', 'Scotch Game', 'Skotu partija', 'C'],
            ['e4 e5 Nf3 Nc6 Bc4 Bc5 b4', 'C51', 'Evans Gambit', 'Evansa gambīts', 'C'],
            ['e4 e5 Nf3 Nc6 Bc4 Nf6', 'C55', 'Two Knights Defence', 'Divu jātnieku aizsardzība', 'C'],
            ['e4 e5 Nf3 Nc6 Bc4 Bc5', 'C53', 'Italian, Giuoco Piano', 'Itāliešu partija, Giuoco Piano', 'C'],
            ['e4 e5 Nf3 Nc6 Bc4', 'C50', 'Italian Game', 'Itāliešu partija', 'C'],
            ['e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7', 'C84', 'Ruy Lopez, Closed', 'Spāņu partija, slēgtā aizsardzība', 'C'],
            ['e4 e5 Nf3 Nc6 Bb5 Nf6', 'C65', 'Ruy Lopez, Berlin', 'Spāņu partija, Berlīnes aizsardzība', 'C'],
            ['e4 e5 Nf3 Nc6 Bb5 a6 Bxc6', 'C68', 'Ruy Lopez, Exchange', 'Spāņu partija, Apmaiņas variante', 'C'],
            ['e4 e5 Nf3 Nc6 Bb5 a6', 'C68', 'Ruy Lopez, Morphy', 'Spāņu partija, Morfi aizsardzība', 'C'],
            ['e4 e5 Nf3 Nc6 Bb5', 'C60', 'Ruy Lopez', 'Spāņu partija', 'C'],
            ['e4 e5 Nf3 Nc6', 'C44', 'Open Game, Knights', 'Atklātā spēle, jātnieku variante', 'C'],
            ['e4 e5 Nf3', 'C40', 'Open Game', 'Atklātā spēle', 'C'],
            ['e4 e5', 'C20', 'Open Game', 'Atklātā spēle', 'C'],
            ['d4 d5 c4 e6 Nc3 Nf6 Bg5', 'D50', "Queen's Gambit, Orthodox", 'Dāmas gambīts, ortodoksā aizsardzība', 'D'],
            ['d4 d5 c4 dxc4', 'D20', "Queen's Gambit Accepted", 'Dāmas gambīts, pieņemtais', 'D'],
            ['d4 d5 c4 c6', 'D10', 'Slav Defence', 'Slāvu aizsardzība', 'D'],
            ['d4 d5 c4 e6', 'D30', "Queen's Gambit Declined", 'Dāmas gambīts, noraidītais', 'D'],
            ['d4 d5 c4', 'D06', "Queen's Gambit", 'Dāmas gambīts', 'D'],
            ['d4 d5 Bf4', 'D02', 'London System', 'Londonas sistēma', 'D'],
            ['d4 d5 Nf3 Nf6', 'D02', "Queen's Pawn Game", 'Dāmas bandinieka spēle', 'D'],
            ['d4 d5', 'D00', "Queen's Pawn Game", 'Dāmas bandinieka spēle', 'D'],
            ['d4 Nf6 c4 g6 Nc3 d5', 'D70', 'Grünfeld Defence', 'Grīnfelda aizsardzība', 'D'],
            ['d4 Nf6 c4 e6 g3', 'E01', 'Catalan Opening', 'Katalāņu atklātne', 'E'],
            ['d4 Nf6 c4 e6 Nc3 Bb4', 'E20', 'Nimzo-Indian Defence', 'Nimcoviča aizsardzība', 'E'],
            ['d4 Nf6 c4 e6', 'E00', 'Indian Defence', 'Indiešu aizsardzība', 'E'],
            ['d4 Nf6 c4 g6 Nc3 Bg7 e4 d6', 'E70', "King's Indian, Main Line", 'Karaļindiešu aizsardzība, galvenā līnija', 'E'],
            ['d4 Nf6 c4 g6 Nc3 Bg7', 'E60', "King's Indian Defence", 'Karaļindiešu aizsardzība', 'E'],
            ['d4 Nf6 c4 g6', 'E60', "King's Indian Defence (general)", 'Karaļindiešu aizsardzība (vispārīgā)', 'E'],
            ['d4 Nf6 c4', 'A15', 'Indian Defence', 'Indiešu aizsardzība', 'E'],
            ['d4 Nf6', 'A46', 'Indian Defence', 'Indiešu aizsardzība', 'E'],
        ];

        // Explanations keyed by "ECO:English name" to avoid collisions
        // when multiple openings share the same ECO code
        $explanations = [
            'Sicilian Defence' => ['Sicīliešu aizsardzība ir melnā populārākais atbildes gājiens uz 1.e4. Melnais cīnās par centra kontroli asimetriski — ar c-bandinieku.',
                ['Melnais rada asimetrisku spēli', 'c5 kontrolē d4 laukumu', 'Melnais uzbrūk dāmas flangā, baltais — karaļa flangā', 'Rada sarežģītas, taktiskas pozīcijas'],
                [['e4', 'Baltais aizņem centru un atver diagonāles laidnim un dāmai.'], ['c5', 'Melnais uzreiz izaicina d4 laukumu! Ja baltais spēlēs d4, melnais apmainīs flanga bandinieku pret centra bandinieku.']]],
            'Sicilian, Najdorf' => ['Nadžorfa variante ir visasākā Sicīliešu līnija. Gājiens a6 sagatavo b5 pretuzbrukumu un saglabā elastību.',
                ['a6 novērš Lb5 un sagatavo b5 paplašināšanos', 'Melnais iegūst aktīvu spēli dāmas flangā', 'Viena no visanalizētākajām atklātnēm šaha vēsturē'],
                [['e4', 'Centra kontrole.'], ['c5', 'Sicīliešu aizsardzība.'], ['Nf3', 'Attīsta zirgu un uzbrūk d4.'], ['d6', 'Atbalsta e5 un ļauj Lg7.'], ['d4', 'Baltais atver centru.'], ['cxd4', 'Apmaiņa — melnais iegūst atvērtu c-līniju.'], ['Nxd4', 'Zirgs centrā.'], ['Nf6', 'Uzbrūk e4.'], ['Nc3', 'Aizsargā e4.'], ['a6', 'Nadžorfa gājiens! Novērš Lb5, sagatavo b5.']]],
            'Sicilian, Dragon' => ['Pūķa variante ir agresīva sistēma, kur melnais fianchetto laidni g7, radot spēcīgu diagonāli.',
                ['Laidnis g7 kontrolē garo diagonāli', 'Melnais rokē īso roku un uzbrūk dāmas flangā', 'Viens no asākajiem variantiem šahā'],
                [['e4', 'Centra kontrole.'], ['c5', 'Sicīliešu aizsardzība.'], ['Nf3', 'Attīsta zirgu.'], ['d6', 'Sagatavo attīstību.'], ['d4', 'Atver centru.'], ['cxd4', 'Apmaiņa.'], ['Nxd4', 'Zirgs centrā.'], ['Nf6', 'Uzbrūk e4.'], ['Nc3', 'Aizsargā e4.'], ['g6', 'Pūķa pazīme! Sagatavo Lg7 fianchetto.']]],
            'Ruy Lopez' => ['Spāņu partija ir viena no vecākajām un stratēģiski bagātākajām atklātnēm. Baltais izveido spiedienu uz e5 caur zirgu c6.',
                ['Laidnis b5 izveido spiedienu uz zirgu c6, kas aizsargā e5', 'Baltais tiecas iegūt ilgtermiņa pozicionālu pārsvaru', 'Bieži rodas sarežģītas vidussagrā manēvru spēles'],
                [['e4', 'Klasiskais karaļa bandinieka gājiens — kontrolē centru.'], ['e5', 'Melnais atbild simetriski.'], ['Nf3', 'Uzbrūk e5 un attīsta figūru.'], ['Nc6', 'Aizsargā e5 un attīsta figūru.'], ['Bb5', 'Spāņu laidnis! Piesalis zirgu c6, kas aizsargā e5. Draud ilgtermiņa spiedienu.']]],
            'Italian Game' => ['Itāliešu partija ir dabiska atklātne, kur laidnis kontrolē centru un mērķē uz f7 — melnā vājāko punktu.',
                ['Laidnis c4 kontrolē d5 un mērķē uz f7', 'f7 ir vājākais laukums spēles sākumā — to aizsargā TIKAI karalis', 'Baltais bieži spēlē d3 vai d4, veidojot centru'],
                [['e4', 'Centra kontrole.'], ['e5', 'Simetriskā atbilde.'], ['Nf3', 'Uzbrūk e5 un attīsta.'], ['Nc6', 'Aizsargā e5.'], ['Bc4', 'Itāliešu laidnis! Kontrolē d5 un mērķē uz f7.']]],
            'Scotch Game' => ['Skotu partija ir tieša atklātne, kur baltais nekavējoties atver centru ar d4.',
                ['Baltais uzreiz atver centru', 'Rada atvērtu, taktisku spēli', 'Populāra alternatīva Spāņu partijai'],
                [['e4', 'Centra kontrole.'], ['e5', 'Simetriskā atbilde.'], ['Nf3', 'Uzbrūk e5.'], ['Nc6', 'Aizsargā e5.'], ['d4', 'Skotu gājiens! Uzreiz atver centru.']]],
            "King's Gambit" => ['Karaļa gambīts ir agresīva atklātne, kur baltais upurē f-bandinieku, lai ātri atvērtu f-līniju un attīstītu figūras.',
                ['Baltais upurē bandinieku par ātru attīstību', 'f-līnija atveras uzbrukumam', 'Romantiskā šaha ēras populārākā atklātne'],
                [['e4', 'Centra kontrole.'], ['e5', 'Simetriskā atbilde.'], ['f4', 'Karaļa gambīts! Upurē bandinieku.']]],
            "Petrov's Defence" => ['Petrova aizsardzība ir solīda un simetriska — melnais uzreiz uzbrūk e4 tā vietā, lai aizsargātu e5.',
                ['Ļoti simetriska spēle', 'Bieži rada mierīgas, pozicionālas pozīcijas', 'Populāra augstā līmenī'],
                [['e4', 'Centra kontrole.'], ['e5', 'Simetriskā atbilde.'], ['Nf3', 'Uzbrūk e5.'], ['Nf6', 'Petrova aizsardzība! Tā vietā, lai aizsargātu e5, melnais pretuzbrūk e4.']]],
            'Evans Gambit' => ['Evansa gambīts ir agresīva līnija Itāliešu partijā — baltais upurē b4 bandinieku par tempu un centru.',
                ['Baltais upurē bandinieku par ātru attīstību', 'Pēc b4 melnais laidnis tiek nobīdīts', 'Rada asas uzbrukuma pozīcijas'],
                [['e4', 'Centra kontrole.'], ['e5', 'Simetriskā atbilde.'], ['Nf3', 'Uzbrūk e5.'], ['Nc6', 'Aizsargā.'], ['Bc4', 'Itāliešu laidnis.'], ['Bc5', 'Simetriskā attīstība.'], ['b4', 'Evansa gambīts! Upurē bandinieku.']]],
            'French Defence' => ['Francūzu aizsardzība ir stabila, pozicionāla atbilde uz 1.e4. Melnais ļauj baltajam aizņemt centru, bet pēc tam to apstrīd ar d5.',
                ['Melnais vispirms spēlē e6, sagatavojot d5', 'Rada slēgtākas pozīcijas', 'Melnā laidnis c8 bieži ir problēma — iesprostots aiz e6'],
                [['e4', 'Centra kontrole.'], ['e6', 'Francūzu aizsardzība! Sagatavo d5, kas tieši izaicina e4.']]],
            'Caro-Kann Defence' => ['Karo-Kann aizsardzība ir viena no stabilākajām atbildēm uz 1.e4. c6 sagatavo d5 bez laidņa c8 bloķēšanas.',
                ['c6 sagatavo d5 bez laidņa bloķēšanas (atšķirībā no Francūzu e6)', 'Melnais iegūst stabilu bandinieku struktūru', 'Rada pozicionālas spēles'],
                [['e4', 'Centra kontrole.'], ['c6', 'Sagatavo d5! Atšķirībā no e6, c6 neaizslēdz laidni c8.']]],
            'Scandinavian Defence' => ['Skandināvu aizsardzība ir vienkārša un tieša — melnais uzreiz izaicina e4.',
                ['Melnais tūlīt nojauc baltā centra bandinieku', 'Ja 2...Dxd5, dāma tiek uzbrukta ar Nc3', 'Vienkārša atklātne, bet melnais parasti nedaudz pasīvāks'],
                [['e4', 'Centra kontrole.'], ['d5', 'Skandināvu aizsardzība! Uzreiz izaicina e4 — vistiešākā atbilde.']]],
            "Queen's Gambit" => ['Dāmas gambīts ir viena no vecākajām atklātnēm. Baltais piedāvā c4 bandinieku, lai iegūtu centra kontroli.',
                ['c4 izaicina melnā d5', 'Ja melnais pieņem (dxc4), baltais iegūst centru', 'Šis nav īsts gambīts — baltais gandrīz vienmēr atgūst bandinieku'],
                [['d4', 'Centra kontrole ar dāmas bandinieku.'], ['d5', 'Melnais arī aizņem centru.'], ['c4', 'Dāmas gambīts! Piedāvā c-bandinieku. Ja dxc4, baltais iegūst brīvu d4 un var spēlēt e4.']]],
            "Queen's Gambit Declined" => ['Noraidītais dāmas gambīts — melnais aizsargā d5 ar e6 un saglabā stabilu centru.',
                ['Melnais saglabā bandinieku d5', 'e6 veido stabilu bet pasīvu struktūru', 'Klasiskā pozicionālā aizsardzība'],
                [['d4', 'Centra kontrole.'], ['d5', 'Melnais aizņem centru.'], ['c4', 'Dāmas gambīts.'], ['e6', 'Melnais noraida gambītu un aizsargā d5.']]],
            "Queen's Gambit Accepted" => ['Pieņemtais dāmas gambīts — melnais ņem c4 bandinieku, bet ļauj baltajam dominēt centrā.',
                ['Melnais iegūst bandinieku, bet zaudē centru', 'Baltais parasti atgūst bandinieku ar Lxc4', 'Melnajam jāspēlē aktīvi, lai kompensētu centra trūkumu'],
                [['d4', 'Centra kontrole.'], ['d5', 'Melnais aizņem centru.'], ['c4', 'Dāmas gambīts.'], ['dxc4', 'Melnais pieņem gambītu!']]],
            'Slav Defence' => ['Slāvu aizsardzība — melnais aizsargā d5 ar c6, saglabājot laidni c8 brīvu.',
                ['c6 aizsargā d5 bez laidņa c8 bloķēšanas', 'Stabilāka nekā Francūzu aizsardzība', 'Populāra augstā līmenī'],
                [['d4', 'Centra kontrole.'], ['d5', 'Melnais aizņem centru.'], ['c4', 'Dāmas gambīts.'], ['c6', 'Slāvu aizsardzība! c6 aizsargā d5 un neaizslēdz laidni c8.']]],
            'London System' => ['Londonas sistēma ir universāla baltā atklātne, ko var spēlēt pret gandrīz jebko. Vienkārša, bet efektīva.',
                ['Baltais vienmēr spēlē d4, Bf4, e3, Nf3, c3', 'Laidnis f4 ir atslēgas gājiens', 'Vienkārša plāna sistēma — nav jāmācās daudz teorijas'],
                [['d4', 'Centra kontrole.'], ['d5', 'Melnais arī aizņem centru.'], ['Bf4', 'Londonas sistēmas pazīme! Laidnis iziet PIRMS e3, jo pēc e3 tam nebūtu ceļa ārā.']]],
            'Grünfeld Defence' => ['Grīnfelda aizsardzība — melnais ļauj baltajam izveidot lielu centru un tad to uzbrūk.',
                ['Melnais izaicina baltā centru ar d5', 'Laidnis g7 spiež centru no tālienes', 'Dinamiska un taktiska aizsardzība'],
                [['d4', 'Centra kontrole.'], ['Nf6', 'Indiešu aizsardzība.'], ['c4', 'Pastiprina centru.'], ['g6', 'Sagatavo fianchetto.'], ['Nc3', 'Attīsta zirgu.'], ['d5', 'Grīnfelda gājiens! Uzreiz izaicina baltā centru.']]],
            "King's Indian Defence" => ['Karaļindiešu aizsardzība ir agresīva melnā sistēma ar fianchetto laidni g7.',
                ['Melnais fianchetto laidni uz g7', 'Pēc rokādes melnais spēlē e5 vai c5', 'Rada asas, taktiskas pozīcijas', 'Fišera un Kasparova mīļākā aizsardzība'],
                [['d4', 'Centra kontrole.'], ['Nf6', 'Indiešu aizsardzība — saglabā elastību.'], ['c4', 'Baltais pastiprina centru.'], ['g6', 'Karaļindiešu pazīme! Sagatavo Lg7 fianchetto.']]],
            'Nimzo-Indian Defence' => ['Nimcoviča aizsardzība — melnais piespiež zirgu c3 ar laidni b4, radot dubultu bandinieku draudus.',
                ['Lb4 piespiež zirgu c3', 'Ja baltais apmaina, rodas dubulti bandinieki', 'Viena no stabilākajām atklātnēm'],
                [['d4', 'Centra kontrole.'], ['Nf6', 'Indiešu aizsardzība.'], ['c4', 'Pastiprina centru.'], ['e6', 'Sagatavo Lb4.'], ['Nc3', 'Attīsta zirgu.'], ['Bb4', 'Nimcoviča gājiens! Piespiež zirgu c3.']]],
            'Catalan Opening' => ['Katalāņu atklātne — baltais apvieno d4+c4 ar fianchetto laidni g2, radot pozicionālu spiedienu.',
                ['Laidnis g2 kontrolē garo diagonāli', 'Baltais iegūst ilgtermiņa spiedienu', 'Populāra elites līmenī'],
                [['d4', 'Centra kontrole.'], ['Nf6', 'Indiešu aizsardzība.'], ['c4', 'Pastiprina centru.'], ['e6', 'Sagatavo d5.'], ['g3', 'Katalāņu pazīme! Sagatavo Lg2 fianchetto.']]],
            'Dutch Defence' => ['Holandiešu aizsardzība — melnais agresīvi uzbrūk karaļa flangā ar f5.',
                ['f5 kontrolē e4 laukumu', 'Melnais plāno uzbrukumu karaļa flangā', 'Riskanta, bet aktīva aizsardzība'],
                [['d4', 'Centra kontrole.'], ['f5', 'Holandiešu aizsardzība! Agresīvs gājiens — kontrolē e4.']]],
            'English Opening' => ['Angļu atklātne — baltais sāk ar c4, kontrolējot d5 no flanga.',
                ['c4 kontrolē d5 laukumu', 'Elastīga atklātne — var pārvērsties daudzās sistēmās', 'Populāra augstā līmenī'],
                [['c4', 'Angļu atklātne! Kontrolē d5 no flanga — elastīgs sākums.']]],
            "Bird's Opening" => ['Bērda atklātne — baltais agresīvi sāk ar f4, kontrolējot e5.',
                ['f4 kontrolē e5 laukumu', 'Retāk sastopama, bet pārsteidzoša', 'Var radīt Holandiešu tipa pozīcijas ar pretēju krāsu'],
                [['f4', 'Bērda atklātne! Kontrolē e5 — agresīvs pirmais gājiens.']]],
            'Pirc Defence' => ['Pīrca aizsardzība — melnais attīsta zirgu un fianchetto laidni, ļaujot baltajam izveidot centru.',
                ['Melnais ļauj baltajam aizņemt centru un tad to apstrīd', 'Elastīga sistēma ar fianchetto', 'Rada sarežģītas, stratēģiskas pozīcijas'],
                [['e4', 'Centra kontrole.'], ['d6', 'Melnais sagatavo fianchetto sistēmu.']]],
            'Modern Defence' => ['Modernā aizsardzība — melnais sāk ar g6 bez Nf6, radot hipermoderrnu sistēmu.',
                ['g6 sagatavo laidņa fianchetto', 'Melnais izaicina baltā centru vēlāk', 'Elastīga bet riskanta pieeja'],
                [['e4', 'Centra kontrole.'], ['g6', 'Modernā aizsardzība! Sagatavo fianchetto bez zirga f6.']]],
        ];

        $sortOrder = 0;
        foreach ($openings as [$moves, $eco, $name, $nameLv, $cat]) {
            $expl = $explanations[$name] ?? null;
            Opening::create([
                'eco' => $eco,
                'category' => $cat,
                'name' => $name,
                'name_lv' => $nameLv,
                'moves' => $moves,
                'summary_lv' => $expl[0] ?? null,
                'ideas_lv' => $expl[1] ?? null,
                'move_explanations_lv' => $expl ? array_map(fn($m) => ['move' => $m[0], 'text' => $m[1]], $expl[2]) : null,
                'sort_order' => $sortOrder++,
            ]);
        }

        $this->command->info('Seeded ' . Opening::count() . ' openings.');
    }
}
